version: "3.7"

# declare namenode, storage_nodes and client
services:
  namenode:
    image: tilammm/dfs:namenode
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == de53bfbeaed6  # change to your node id

    environment:
      STORAGE1_HOST: storage_node1
      STORAGE2_HOST: storage_node2
      STORAGE3_HOST: storage_node3
      # add more storage_nodes if needed


  storage_node1:
    image: tilammm/dfs:storage_node
    deploy:
      placement:
        constraints:
          - node.id == 1b799e6858ae  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18000
      SERVER_PORT: 8000


  storage_node2:
    image: tilammm/dfs:storage_node
    deploy:
      placement:
        constraints:
          - node.id == 88106203d911  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18800
      SERVER_PORT: 8000

  storage_node3:
    image: tilammm/dfs:storage_node
    deploy:
      placement:
        constraints:
          - node.id == de53bfbeaed6  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18000
      SERVER_PORT: 8000

  client:
    image: tilammm/dfs:client
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == 76d489fb0442  # change to your node id
    environment:
      SERVER_IP: namenode
      SERVER_PORT: 8800
