version: "3.7"

# declare namenode, datanodes and client
services:
  namenode:
    image: khabibullin/namenode:develop
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == de53bfbeaed6  # change to your node id

    environment:
      DATANODE1_HOST: datanode1
      DATANODE2_HOST: datanode2
      DATANODE3_HOST: datanode3
      # add more datanodes if needed


  datanode1:
    image: khabibullin/datanode:develop
    deploy:
      placement:
        constraints:
          - node.id == 1b799e6858ae  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18000
      SERVER_PORT: 8000


  datanode2:
    image: khabibullin/datanode:develop
    deploy:
      placement:
        constraints:
          - node.id == 88106203d911  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18800
      SERVER_PORT: 8000

  datanode3:
    image: khabibullin/datanode:develop
    deploy:
      placement:
        constraints:
          - node.id == de53bfbeaed6  # change to your node id

    environment:
      SERVER_IP: namenode
      PORT: 18000
      SERVER_PORT: 8000

  client:
    image: khabibullin/client:develop
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.id == 76d489fb0442  # change to your node id
    environment:
      SERVER_IP: namenode
      SERVER_PORT: 8800
